import 'package:flutter/material.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedNavmenuWidget1.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedHeaderWidget5.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedEditProfileWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedVectorWidget37.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/heydocapp/generatededitprofilewidget/generated/GeneratedVectorWidget36.dart';

/* Frame Edit Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 218.0,
                child: GeneratedVector1Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 27.0,
                child: GeneratedHeaderWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 68.0,
                child: GeneratedNavmenuWidget1(),
              ),
              Positioned(
                left: 145.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 26.0,
                child: GeneratedEditProfileWidget1(),
              ),
              Positioned(
                left: 34.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedGroup19Widget(),
              ),
              Positioned(
                left: 118.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 139.0,
                child: GeneratedEllipse9Widget(),
              ),
              Positioned(
                left: 213.0,
                top: 224.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 28.0,
                child: GeneratedEllipse10Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.013333333333333334;
                  double scaleX = (constraints.maxWidth * percentWidth) / 5.0;

                  double percentHeight = 0.006157635467980296;
                  double scaleY = (constraints.maxHeight * percentHeight) / 5.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6,
                        translateY: constraints.maxHeight * 0.29064039408866993,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget36())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.034666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 13.0;

                  double percentHeight = 0.014778325123152709;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 12.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5893333333333334,
                        translateY: constraints.maxHeight * 0.2857142857142857,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget37())
                  ]);
                }),
              ),
              Positioned(
                left: 34.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 59.0,
                child: GeneratedGroup16Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 59.0,
                child: GeneratedGroup15Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 59.0,
                child: GeneratedGroup14Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 59.0,
                child: GeneratedGroup17Widget(),
              )
            ]),
      ),
    ));
  }
}
