import 'package:flutter/material.dart';

/* Rectangle Rectangle 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 4075.0,
      height: 2626.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(268.0),
        border: Border.all(
          width: 11.0,
          color: Color.fromARGB(165, 0, 0, 0),
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(268.0),
        child: Container(
          color: Color.fromARGB(255, 235, 198, 77),
        ),
      ),
    ));
  }
}
