import 'package:flutter/material.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedGroup41Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedGetAppointmentWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedScheduleWidget2.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedGroup38Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedGroup37Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedGroupWidget19.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedHeaderWidget7.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedRsPastiSembuhCileungsiBogorWidget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/Generated50Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedRectangle14Widget3.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedWorkingTimeWidget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedNavmenuWidget3.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedDrSutejoMahmudWidget1.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedVectorWidget51.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedWedFri0800AM1400PMWidget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedGroup40Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/Generated1000Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedPsychiatristWidget2.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/Generated20Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedGroup39Widget.dart';
import 'package:flutterapp/heydocapp/generateddoctorwidget/generated/GeneratedGroupWidget18.dart';

/* Frame Doctor
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDoctorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle14Widget3(),
              ),
              Positioned(
                left: 50.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 335.0,
                child: Generated20Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 501.0,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 27.0,
                child: GeneratedHeaderWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 68.0,
                child: GeneratedNavmenuWidget3(),
              ),
              Positioned(
                left: 34.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedGroup20Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 29.0,
                child: GeneratedDrSutejoMahmudWidget1(),
              ),
              Positioned(
                left: 34.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 29.0,
                child: GeneratedPsychiatristWidget2(),
              ),
              Positioned(
                left: 34.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 23.0,
                child: GeneratedWorkingTimeWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 23.0,
                child: GeneratedRsPastiSembuhCileungsiBogorWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 53.0,
                child: GeneratedGroup40Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 23.0,
                child: GeneratedWedFri0800AM1400PMWidget(),
              ),
              Positioned(
                left: 274.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 18.0,
                child: GeneratedGroup37Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 26.0,
                child: GeneratedScheduleWidget2(),
              ),
              Positioned(
                left: 34.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 66.0,
                child: GeneratedFrame5Widget(),
              ),
              Positioned(
                left: 89.0,
                top: 685.0,
                right: null,
                bottom: null,
                width: 253.0,
                height: 40.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 154.0,
                top: 694.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 23.0,
                child: GeneratedGetAppointmentWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 685.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 40.0,
                child: GeneratedRectangle35Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.0666666514078776;

                  final double height =
                      constraints.maxHeight * 0.0277093690017174;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.18133333333333335,
                        y: constraints.maxHeight * 0.8559113300492611,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget18(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 250.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 53.0,
                child: GeneratedGroup38Widget(),
              ),
              Positioned(
                left: 293.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 26.0,
                child: Generated50Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.032;
                  double scaleX = (constraints.maxWidth * percentWidth) / 12.0;

                  double percentHeight = 0.014778325123152709;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 12.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.736,
                        translateY: constraints.maxHeight * 0.5763546798029556,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget51())
                  ]);
                }),
              ),
              Positioned(
                left: 143.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 53.0,
                child: GeneratedGroup39Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.04202393341064453;

                  final double height =
                      constraints.maxHeight * 0.01600985221674877;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.4,
                        y: constraints.maxHeight * 0.5751231527093597,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget19(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05090931193033854;

                  final double height =
                      constraints.maxHeight * 0.01724119139422337;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12133333333333333,
                        y: constraints.maxHeight * 0.5738916256157636,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup41Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 71.5,
                top: 465.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 26.0,
                child: Generated1000Widget(),
              )
            ]),
      ),
    ));
  }
}
